function exit_sequence(file_path,position)

if nargin < 2
    position = [1 1 1280 780];
end

% Needed here for backing up the data before final saving
global data setup test

% position = [1 1 1280 780];
% file_path = '';

mkdir(file_path,'feedbacks');
feedback_path = [file_path 'feedbacks' filesep date '_' ...
    test.subject '.txt'];

set(0,'DefaultFigureMenu','none', 'DefaultFigureNumberTitle', 'off');

h_fig = figure('position',position, ...
    'name','Thank you for participation!',...
    'tag','thanks');

if setup.feedback == 1
% Edit box for feedback
uicontrol(h_fig, ...
    'Style','edit', ...
    'Units', 'normalized', ...
    'Position',[.2 .45 .6 .25], ...
    'CallBack',{@feedback_function,feedback_path},...
    'tag','textBox1', ...
    'BackgroundColor', 'w',...
    'fontsize',12,...
    'max',3,...
    'min',1,...
    'horizontal','left');

% Question string for feedback box
uicontrol(h_fig, ...
    'Style','text', ...
    'Units', 'normalized', ...
    'Position',[.2 .73 .6 .04], ...
    'fontsize',14,...
    'string',setup.feedback_text,...
    'horizontal','left',...
    'back',[0.8 0.8 0.8],...
    'fore',[0.1 0.1 0.1]);
end

uicontrol('style','pushbutton', ...
    'Units', 'Normalized', ...
    'position',[0.3 0.1 0.4 0.09],...
    'CallBack',{@save_button,file_path}, ...
    'tag','filebutton', ...
    'string','Push this button to end the experiment', ...
    'FontSize', 13);

%%%Callback functions------------------------------------------------------

    function feedback_function(source,~,file_path)
        subject_feedback = get(source,'string');
        dlmwrite(file_path,subject_feedback,...
            'delimiter', '',...
            'newline', 'pc');
    end

    function save_button(source,~,file_path)
                
        % Make backup data file before saving
        save(strcat(file_path,'backup_data.mat'),'data');
        
        % Save data to Excel
        set(source,'enable','off',...
            'string','Please wait...');
        drawnow;
        save_data();
    end

end